name: launchpipeline
description: A Flutter package to handle launch tasks
version: 1.0.0
# repository: https://gitlab.com/next-top-tech/application/core/release/launchpipeline

environment:
  sdk: '>=3.4.3 <4.0.0'

# Add regular dependencies here.
dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  flutter_lints: ^5.0.0
